import type { Category } from './types';
import {
  Car,
  Home,
  Utensils,
  ShoppingBasket,
  Heart,
  Film,
  Plane,
  Gift,
  GraduationCap,
  Briefcase,
  PiggyBank,
  Pizza,
  Bus,
  Train,
  Shirt,
  BookOpen,
  DollarSign,
} from 'lucide-react';

export const categories: Omit<Category, 'id'>[] = [
  { name: 'Lebensmittel' },
  { name: 'Wohnen' },
  { name: 'Transport' },
  { name: 'Essen gehen' },
  { name: 'Gesundheit' },
  { name: 'Unterhaltung' },
  { name: 'Reisen' },
  { name: 'Geschenke' },
  { name: 'Bildung' },
  { name: 'Arbeit' },
  { name: 'Sparen' },
  { name: 'Kleidung' },
  { name: 'Haushalt' },
  { name: 'Einnahmen' },
];
